#!/usr/bin/python

from Adafruit_CharLCDPlate import Adafruit_CharLCDPlate
from time import sleep
import socket
from NotificationCenter import NotificationCenter

lcd = Adafruit_CharLCDPlate(1)

NC_METHODS = {
    'status_date':     [lcd.WHITE,  30],
    'status_weather':  [lcd.WHITE,  30],
    'status_torrents': [lcd.YELLOW, 10],
    'status_disk':     [lcd.YELLOW, 10],
    }

lcd.clear()
lcd.backlight(lcd.RED)

nc = NotificationCenter()
lcd.message("\n".join(nc.startup()))
sleep(5)

""" Try to keep the weather request from tying things up """
socket.setdefaulttimeout(2)

while True:
    for NC_METHOD, (LCD_BK, NC_SLEEP) in NC_METHODS.iteritems():
        res = getattr(nc, nc.STATIC_MODE or NC_METHOD)()
        if len(res):
            lcd.clear()
            lcd.message("\n".join(res))
            if not nc.STATIC_MODE:
                lcd.backlight(LCD_BK)
                sleep(NC_SLEEP)
            else:
                sleep(3)
