#!/usr/bin/python

from Adafruit_CharLCDPlate import Adafruit_CharLCDPlate
from time import sleep
import socket
from NotificationCenter import NotificationCenter

lcd = Adafruit_CharLCDPlate(1)

NC_METHODS = {
    'status_date': lcd.GREEN,
    'status_weather': lcd.BLUE,
    'fun1': lcd.RED,
    'status_torrents': lcd.BLUE
    }

lcd.clear()
lcd.backlight(lcd.RED)

nc = NotificationCenter()
lcd.message("\n".join(nc.startup()))

""" Try to keep the weather request from tying things up """
socket.setdefaulttimeout(2)

while True:
    for NC_METHOD, LCD_BK in NC_METHODS:
        res = getattr(nc, NC_METHOD)()
        if len(res):
            lcd.clear()
            lcd.backlight(LCD_BK)
            lcd.message("\n".join(res))
            sleep(15)
