#!/usr/bin/env python

import os
import sys

# FUNCTIONS
def pwm(pin, angle):
    angle = checkmax(angle)
    print "servo[" + str(pin) + "][" + str(angle) + "]"
    cmd = "echo " + str(pin) + "=" + str(angle) + " > /dev/servoblaster"
    os.system(cmd)

def checkmax(angle): #PWM can only handle 249 units, so we're simply cutting the hex values 250-255 down to 249
    if angle > 249:
        angle = 249
    return angle

def setcolor(hex):
    pwm(5, int(hex[1:3],16))
    pwm(6, int(hex[3:5],16))
    pwm(2, int(hex[5:7],16))

setcolor("#" + sys.argv[1])
# setcolor("#708090")
