#!/usr/bin/env python

from time import sleep
import signal, sys, os

GPIO = [5, 6, 2]
STEP = 5
SYS_DELAY = 1

def pwm(pin, angle, delay):
    cmd = "echo " + str(pin) + "=" + str(angle) + " > /dev/servoblaster"
    os.system(cmd)
    sleep(delay)

def signal_handler(signal, frame):
    for i in GPIO:
        pwm(i, 0, 0)
    sys.exit(0)

if __name__ == '__main__':

    signal.signal(signal.SIGINT, signal_handler)

    while True:
        for i in GPIO:
            for j in range(1, 249, STEP):
                pwm(i, j, SYS_DELAY)
        for i in GPIO:
            for j in range(249, 1, (STEP*-1)):
                pwm(i, j, SYS_DELAY)
